# Генерация систем непрерывных и дискретных случайных величин

1. Написать программу реализующую метод формирования двумерной НСВ с
определенным распределением (согласно варианту). Выполнить статистическое
исследование (построение гистограммы составляющих вектора, вычислить точечные
и интервальные оценки, коэффициент корреляции и другое). Проверить гипотезы о
соответствии полученных оценок характеристик (математическое ожидание,
дисперсия, корреляция) случайной величины теоретическим.  



In [1]:
import numpy as np
from sympy import *
np.random.seed(42)
x, y, z, t = symbols('x y z t')

Функция плотности вероятности будет соответсововать второму варианту

In [2]:
7217057 % 9

2

$$f(x,y) = \frac{3*\sin(x+y)}{4} $$

In [3]:
def Probability_density(x, y):
    return 3*np.sin(x+y)/4

## Двумерная НСВ

### Получение $f(y)$ и $g(y)$
Для получения функция распределения $f(y)$ проинтегрируем $f(x, y)$ по $x$
$$f(y) = \frac{3}{4}\int_0^\infty \mathrm{sin(x+y)}\mathrm{d}x$$

In [4]:
integrate(3/4*sin(x+y), (x, 0, oo))

AccumBounds(-0.75, 0.75) + 0.75*cos(y)

In [5]:
def f_y_star(y):
    return 3/4*np.cos(y)

Мы получили функцию $f(y)=0.75*cos(y)$. Проинтегрировав ее мы получим плотность распределения
$$F(y)= \frac{3}{4}\int_0^\infty \mathrm{cos(y)}\mathrm{d}y$$
и ищем обратную 
$$g(y)= F(y)^{-1}$$  

In [6]:
integrate(3/4*cos(y))#, (y, -oo, np.pi/2))

0.75*sin(y)

Таким образом мы выяснили, что функция распределения для случайной величины $y$: $F(y)=0.75*sin(y)$, а обратная ей функция $$g(y)=\frac{4}{3}*\arcsin(y)$$

In [7]:
def y_inverted(y):
    return np.arcsin(y)/0.75

Согласно свойству функции расприедления, случайные величины, полученные с помощью функции $g(y)$ будут иметь распределение, соотвутствующее функции, заданой по условию.

### Получение $f(x)$ и $g(x)$ 
Чтобы избежать погрешности в случае если x и y зависимы $f(x)$ будем искать как: 
$$ f(x)=\frac{f(x,y)}{f(y)}$$

In [8]:
#integrate(3/4*sin(x)*cos(y) + 3/4*sin(y)*cos(x), (x, 0, oo))

In [9]:
def f_x_star(x,y):
    return (3*np.sin(x+y)/4)/y

In [10]:
y = np.random.random_sample()
#x = y = np.random.random_sample()
y_output = float(f_y_star(y))

In [11]:
const = float("%.3f" % (3/(4*y_output)))
y_output = float("%.3f" % y_output) #обрезаем лишнее символы после запятой

integrate(const*sin(x+y_output))

-1.074*cos(x + 0.698)

проинтегрируем эту функцию - получаем обратную 
$$g(x)= F(x)^{-1}$$  
$$\arccos{(x-0.698)}/1.074 $$

In [12]:
def x_inverted(x):
    return np.arccos(x - 0.698)/1.074

Таким образом, мы получили функции для генерации x и y

### Генерация случайных величин:

In [13]:
n = 10
continuity_array = np.zeros((n,2))

for i in range(n):
    #for j in range(2):
    x = np.random.random_sample()
    y = np.random.random_sample()
    #print(y_inverted(y), x_inverted(x))
    continuity_array[i,0] = y_inverted(y)
    continuity_array[i,1] = x_inverted(x)

In [14]:
#print(continuity_array)

## Двумерная ДСВ

2. Написать программу реализующую метод формирования двумерной ДСВ. Выполнить
статистическое исследование (построение эмпирической матрицы распределения,
гистограммы составляющих вектора, вычислить точечные и интервальные оценки,
коэффициент корреляции). Проверить гипотезы о соответствии закона распределения
полученной случайной величины требуемому. Проверить гипотезы о соответствии
полученных оценок характеристик (математическое ожидание, дисперсия,
корреляция) случайной величины теоретическим

In [15]:
size_discrete = 5
d = np.random.dirichlet(np.ones(size_discrete*size_discrete))
print(d)

[0.00715107 0.01644633 0.02171851 0.02898492 0.0732048  0.01060209
 0.03436814 0.04272067 0.00226401 0.04452127 0.00889924 0.00320172
 0.1415457  0.16043992 0.07864996 0.01729228 0.00489214 0.05487022
 0.02761197 0.00619517 0.03253643 0.00166568 0.11425865 0.01425401
 0.05170511]


In [16]:
np.sum(d)

1.0

In [17]:
x_discrete = np.zeros((size_discrete))
y_discrete = np.zeros((size_discrete))

for i in range(size_discrete):
    repeated = True
    while(repeated):
        x = np.random.randint(1,10)
        if x not in x_discrete: 
            x_discrete[i] = x
            repeated = False
        #else:
            #print(i, x, x_discrete)
            
    repeated = True
    while(repeated):
        y = np.random.randint(1,10)
        if y not in y_discrete: 
            y_discrete[i] = y
            repeated = False
        #print(i, y, y_discrete)
            
x_discrete = np.sort(x_discrete)
y_discrete = np.sort(y_discrete)
print(x_discrete, y_discrete)

[2. 4. 6. 7. 8.] [4. 5. 6. 8. 9.]


In [18]:
p_x = np.zeros((size_discrete))
accumulated_sum = 0

for i in range(size_discrete*size_discrete):
    accumulated_sum += d[i]
    print(i, accumulated_sum)
    if (i + 1) % (size_discrete) == 0 and i > 0:
        print("ss", accumulated_sum)
        p_x[int(i / size_discrete)] = accumulated_sum
        accumulated_sum = 0

0 0.0071510708027131935
1 0.0235973958299588
2 0.04531590968161866
3 0.07430082482729981
4 0.1475056293292294
ss 0.1475056293292294
5 0.010602089505511801
6 0.044970231456660334
7 0.08769090201238688
8 0.08995491189173359
9 0.13447618613834966
ss 0.13447618613834966
10 0.008899240151915315
11 0.012100961728582264
12 0.15364666454851172
13 0.3140865876001494
14 0.3927365502075347
ss 0.3927365502075347
15 0.01729227781662418
16 0.022184414549249576
17 0.07705463908838453
18 0.1046666050090981
19 0.11086177098075523
ss 0.11086177098075523
20 0.03253642599203729
21 0.03420210552531495
22 0.14846075278579038
23 0.16271475805842214
24 0.21441986334413127
ss 0.21441986334413127


In [19]:
print(p_x)

[0.14750563 0.13447619 0.39273655 0.11086177 0.21441986]


In [20]:
f_x = np.zeros((size_discrete))
accumulated_sum = 0
for i in range(size_discrete):
    accumulated_sum += p_x[i]
    f_x[i] = accumulated_sum
    
f_x

array([0.14750563, 0.28198182, 0.67471837, 0.78558014, 1.        ])

In [21]:
p_y = np.zeros((size_discrete,size_discrete))

for i in range(size_discrete):
    for j in range(size_discrete):
        p_y[i, j] = d[i*size_discrete + j]/p_x[i]

In [22]:
p_y

array([[0.04847999, 0.11149625, 0.14723854, 0.1965004 , 0.49628482],
       [0.0788399 , 0.25557047, 0.31768205, 0.01683577, 0.33107181],
       [0.02265957, 0.00815234, 0.36040878, 0.40851793, 0.20026138],
       [0.15598053, 0.04412826, 0.4949427 , 0.24906661, 0.0558819 ],
       [0.15174166, 0.00776831, 0.53287343, 0.06647707, 0.24113953]])

In [23]:
f_y = np.zeros((size_discrete,size_discrete))
accumulated_sum = 0

for i in range(size_discrete):
    accumulated_sum = 0
    for j in range(size_discrete):
        accumulated_sum += p_y[i,j]
        f_y[i, j] = accumulated_sum
        
f_y

array([[0.04847999, 0.15997624, 0.30721478, 0.50371518, 1.        ],
       [0.0788399 , 0.33441037, 0.65209242, 0.66892819, 1.        ],
       [0.02265957, 0.03081191, 0.39122069, 0.79973862, 1.        ],
       [0.15598053, 0.20010879, 0.69505149, 0.9441181 , 1.        ],
       [0.15174166, 0.15950997, 0.69238339, 0.75886047, 1.        ]])

## generation itself

In [28]:
discrete_array = np.zeros((n,2))

j_saved = 0
for i in range(n):
    x = np.random.random_sample()
    y = np.random.random_sample()   

    for j in range(size_discrete):
        if x < f_x[j]:
            #print(i, x, j,f_x[j], x_discrete[j])
            j_saved = j
            discrete_array[i,0] = x_discrete[j]
            break
        #else: print("smth got wrong with x")
    
    for j in range(size_discrete):
        if y < f_y[j_saved, j]:
            discrete_array[i,1] = y_discrete[j]
            #print(" ", y, j, f_y[j_saved, j], y_discrete[j])
            break
        #else: print("smth got wrong with y")
            
discrete_array

0 0.8074401551640625 4 1.0000000000000002 8.0
  0.8960912999234932 4 0.9999999999999999 9.0
1 0.3180034749718639 2 0.6747183656751137 6.0
  0.11005192452767676 2 0.3912206909881951 6.0
2 0.22793516254194168 1 0.28198181546757906 4.0
  0.4271077886262563 2 0.6520924226849363 6.0
3 0.8180147659224931 4 1.0000000000000002 8.0
  0.8607305832563434 4 0.9999999999999999 9.0
4 0.006952130531190703 0 0.1475056293292294 2.0
  0.5107473025775657 4 1.0 9.0
5 0.417411003148779 2 0.6747183656751137 6.0
  0.22210781047073025 2 0.3912206909881951 6.0
6 0.1198653673336828 0 0.1475056293292294 2.0
  0.33761517140362796 3 0.5037151813471605 8.0
7 0.9429097039125192 4 1.0000000000000002 8.0
  0.32320293202075523 2 0.6923833942917854 6.0
8 0.5187906217433661 2 0.6747183656751137 6.0
  0.7030189588951778 3 0.7997386223262792 8.0
9 0.363629602379294 2 0.6747183656751137 6.0
  0.9717820827209607 4 0.9999999999999999 9.0


array([[8., 9.],
       [6., 6.],
       [4., 6.],
       [8., 9.],
       [2., 9.],
       [6., 6.],
       [2., 8.],
       [8., 6.],
       [6., 8.],
       [6., 9.]])

In [25]:
print(x_discrete, y_discrete)

[2. 4. 6. 7. 8.] [4. 5. 6. 8. 9.]
